# Generated by Django 5.2.17 on 2026-08-31 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GalleryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=100, verbose_name="Nom de la catégorie"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "ordre",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
            ],
            options={
                "verbose_name": "Catégorie d'événement",
                "verbose_name_plural": "Catégories d'événements",
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.CreateModel(
            name="GalleryAlbum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(
                        max_length=200, verbose_name="Titre de l'événement / album"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Description de l'événement"
                    ),
                ),
                (
                    "date_evenement",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de l'événement"
                    ),
                ),
                (
                    "lieu",
                    models.CharField(
                        blank=True,
                        default="Terrain principal, Gombe, Kinshasa",
                        max_length=255,
                        verbose_name="Lieu",
                    ),
                ),
                (
                    "couverture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="gallery/covers/",
                        verbose_name="Image de couverture",
                    ),
                ),
                (
                    "est_publie",
                    models.BooleanField(default=True, verbose_name="Publié en ligne"),
                ),
                (
                    "est_en_vedette",
                    models.BooleanField(
                        default=False,
                        verbose_name="Mettre en vedette (Accueil & Tête de liste)",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="albums",
                        to="gallery.gallerycategory",
                        verbose_name="Catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Album / Événement",
                "verbose_name_plural": "Albums / Événements",
                "ordering": ["-est_en_vedette", "-date_evenement", "-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="GalleryPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="gallery/photos/", verbose_name="Fichier image"
                    ),
                ),
                (
                    "titre",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Titre / Légende courte",
                    ),
                ),
                (
                    "legende",
                    models.TextField(blank=True, verbose_name="Description détaillée"),
                ),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="gallery.galleryalbum",
                        verbose_name="Album",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo d'événement",
                "verbose_name_plural": "Photos d'événements",
                "ordering": ["ordre", "date_ajout"],
            },
        ),
    ]
