# Generated by Django 5.1 on 2025-12-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_contact_parent_profile_ecole_frequente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='telephone_paiement',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
