# Generated by Django 5.2.17 on 2026-09-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_abonnement_telephone_paiement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abonnement",
            name="moyen_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mpesa", "M-Pesa"),
                    ("orange", "Orange Money"),
                    ("airtel", "Airtel Money"),
                    ("cash", "Cash / Espèces"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
