# Generated by Django 5.1 on 2025-11-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Magic Hoops Academy Kinshasa (MHA)', max_length=200)),
                ('slogan', models.CharField(default='Là où le talent rencontre la discipline', max_length=255)),
                ('fondateur', models.CharField(default='Bruno Lobaya Nkoy (alias Magic)', max_length=200)),
                ('description', models.TextField(help_text="Présentation générale de l'académie")),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('objectifs', models.TextField()),
                ('valeurs', models.TextField()),
                ('infrastructures', models.TextField()),
                ('localisation', models.CharField(max_length=255)),
                ('philosophie', models.TextField()),
                ('date_creation', models.DateField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='academy/')),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='academy/')),
            ],
            options={
                'verbose_name': "Informations de l'académie",
                'verbose_name_plural': "Informations de l'académie",
            },
        ),
    ]
