# Generated by Django 5.2.17 on 2026-09-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="MethodPillar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(max_length=150, verbose_name="Titre du pilier"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "icone",
                    models.CharField(
                        default="bi-dribbble",
                        max_length=50,
                        verbose_name="Classe icône Bootstrap",
                    ),
                ),
                (
                    "est_actif",
                    models.BooleanField(default=True, verbose_name="Est actif"),
                ),
            ],
            options={
                "verbose_name": "Pilier de la méthode",
                "verbose_name_plural": "Piliers de la méthode",
                "ordering": ["ordre", "id"],
            },
        ),
        migrations.AddField(
            model_name="academyinfo",
            name="adresse_terrain",
            field=models.CharField(
                default="Avenue de la Science numéro 5, Gombe, Kinshasa",
                max_length=255,
                verbose_name="Adresse du terrain",
            ),
        ),
        migrations.AddField(
            model_name="academyinfo",
            name="coach_magic_bio",
            field=models.TextField(
                default="À Magic Hoops Academy, l'exigence sur le parquet s'accompagne d'une transmission sans compromis du respect et du dépassement de soi.",
                verbose_name="Bio Coach Magic",
            ),
        ),
        migrations.AddField(
            model_name="academyinfo",
            name="coach_magic_quote",
            field=models.TextField(
                default="« Le talent ouvre la voie, mais seule la discipline forge les champions. »",
                verbose_name="Citation Coach Magic",
            ),
        ),
        migrations.AddField(
            model_name="academyinfo",
            name="coach_magic_titre",
            field=models.CharField(
                default="Bruno Lobaya Nkoy, alias Coach Magic.",
                max_length=255,
                verbose_name="Titre Coach Magic",
            ),
        ),
        migrations.AddField(
            model_name="academyinfo",
            name="email",
            field=models.EmailField(
                default="info@magichoops.cd",
                max_length=254,
                verbose_name="Email de contact",
            ),
        ),
        migrations.AddField(
            model_name="academyinfo",
            name="hero_subtitle",
            field=models.TextField(
                default="L'académie de référence à Kinshasa (Gombe) pour développer les fondamentaux techniques, la discipline sportive et l'esprit d'équipe des U10 à U18+.",
                verbose_name="Sous-titre Hero",
            ),
        ),
        migrations.AddField(
            model_name="academyinfo",
            name="hero_title",
            field=models.CharField(
                default="Former les jeunes joueurs, forger les champions.",
                max_length=255,
                verbose_name="Titre Hero",
            ),
        ),
        migrations.AddField(
            model_name="academyinfo",
            name="methode_cadre_texte",
            field=models.TextField(
                default="Au-delà du basketball, nous inculquons la ponctualité, le respect, l'effort collectif et le dépassement de soi.",
                verbose_name="Texte Le Cadre Fait la Différence",
            ),
        ),
        migrations.AddField(
            model_name="academyinfo",
            name="methode_description",
            field=models.TextField(
                default="Une pédagogie sportive complète qui allie rigueur technique, motricité athlétique, intelligence tactique et mental d'acier.",
                verbose_name="Description Méthode",
            ),
        ),
        migrations.AddField(
            model_name="academyinfo",
            name="methode_titre",
            field=models.CharField(
                default="Former le joueur complet, pas seulement le scoreur.",
                max_length=255,
                verbose_name="Titre Méthode",
            ),
        ),
        migrations.AddField(
            model_name="academyinfo",
            name="slogan_badge",
            field=models.CharField(
                default="Formons les champions de demain !",
                max_length=200,
                verbose_name="Badge Slogan",
            ),
        ),
        migrations.AddField(
            model_name="academyinfo",
            name="telephone",
            field=models.CharField(
                default="+243 900 824 429",
                max_length=50,
                verbose_name="Téléphone de contact",
            ),
        ),
        migrations.AlterField(
            model_name="academyinfo",
            name="description",
            field=models.TextField(
                blank=True, default="", help_text="Présentation générale de l'académie"
            ),
        ),
        migrations.AlterField(
            model_name="academyinfo",
            name="infrastructures",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="academyinfo",
            name="localisation",
            field=models.CharField(
                blank=True,
                default="Avenue de la Science numéro 5, Gombe, Kinshasa",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="academyinfo",
            name="mission",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="academyinfo",
            name="objectifs",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="academyinfo",
            name="philosophie",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="academyinfo",
            name="valeurs",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="academyinfo",
            name="vision",
            field=models.TextField(blank=True, default=""),
        ),
    ]
