# Generated by Django 5.2.17 on 2026-08-31 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=200, verbose_name="Nom de l'article"),
                ),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField(verbose_name="Description complète")),
                (
                    "details_matiere",
                    models.CharField(
                        blank=True,
                        help_text="Ex: 100% Polyester respirant Dri-FIT, Impression sérigraphie haute résistance",
                        max_length=255,
                        verbose_name="Matière / Caractéristiques",
                    ),
                ),
                (
                    "prix_usd",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix en USD ($)"
                    ),
                ),
                (
                    "image_principale",
                    models.ImageField(
                        upload_to="shop/products/", verbose_name="Image principale"
                    ),
                ),
                (
                    "en_stock",
                    models.BooleanField(
                        default=True, verbose_name="Disponible en stock"
                    ),
                ),
                (
                    "quantite_stock",
                    models.IntegerField(
                        default=20, verbose_name="Quantité globale en stock"
                    ),
                ),
                (
                    "badge",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Aucun"),
                            ("nouveau", "Nouveau"),
                            ("populaire", "Bestseller / Populaire"),
                            ("officiel", "Officiel MHA"),
                            ("limite", "Édition Limitée"),
                            ("promo", "Promotion"),
                        ],
                        max_length=20,
                        verbose_name="Badge visuel",
                    ),
                ),
                (
                    "est_actif",
                    models.BooleanField(
                        default=True, verbose_name="Visible dans la boutique"
                    ),
                ),
                (
                    "est_en_vedette",
                    models.BooleanField(
                        default=False,
                        verbose_name="Mettre en avant (Accueil / Top boutique)",
                    ),
                ),
                (
                    "guide_tailles",
                    models.TextField(
                        blank=True,
                        help_text="Tailles juniors : U10, U12, U14. Tailles adultes : S, M, L, XL, XXL.",
                        verbose_name="Guide des tailles / Informations complémentaires",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
            ],
            options={
                "verbose_name": "Article / Produit",
                "verbose_name_plural": "Articles / Produits",
                "ordering": ["-est_en_vedette", "-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=100, verbose_name="Nom de la catégorie"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description du rayon"),
                ),
                (
                    "icone_css",
                    models.CharField(
                        default="bi-tag",
                        max_length=50,
                        verbose_name="Icône Bootstrap (ex: bi-tshirt, bi-bag)",
                    ),
                ),
                (
                    "ordre",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
            ],
            options={
                "verbose_name": "Rayon / Catégorie de produit",
                "verbose_name_plural": "Rayons / Catégories de produits",
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_commande",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Numéro de commande"
                    ),
                ),
                (
                    "client_nom",
                    models.CharField(max_length=100, verbose_name="Nom de famille"),
                ),
                (
                    "client_prenom",
                    models.CharField(max_length=100, verbose_name="Prénom"),
                ),
                (
                    "client_telephone",
                    models.CharField(
                        help_text="Numéro utilisé pour la confirmation et le retrait de commande.",
                        max_length=30,
                        verbose_name="Téléphone / WhatsApp",
                    ),
                ),
                (
                    "client_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Adresse Email"
                    ),
                ),
                (
                    "mode_retrait",
                    models.CharField(
                        choices=[
                            (
                                "retrait_terrain",
                                "Retrait gratuit au Terrain MHA (Gombe, Av. de la Science n°5)",
                            ),
                            ("livraison_kinshasa", "Livraison à domicile (Kinshasa)"),
                        ],
                        default="retrait_terrain",
                        max_length=30,
                        verbose_name="Mode de réception",
                    ),
                ),
                (
                    "adresse_livraison",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Adresse exacte (si livraison)",
                    ),
                ),
                (
                    "commune_kinshasa",
                    models.CharField(
                        blank=True,
                        default="Gombe",
                        max_length=100,
                        verbose_name="Commune / Quartier",
                    ),
                ),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("mpesa", "M-Pesa (Vodacom) - +243 810 000 000"),
                            ("orange_money", "Orange Money - +243 890 000 000"),
                            ("airtel_money", "Airtel Money - +243 990 000 000"),
                            (
                                "especes_club",
                                "Paiement en espèces au terrain / secrétariat",
                            ),
                            ("carte", "Carte Bancaire / Paiement en ligne"),
                        ],
                        default="mpesa",
                        max_length=30,
                        verbose_name="Moyen de paiement",
                    ),
                ),
                (
                    "reference_paiement",
                    models.CharField(
                        blank=True,
                        help_text="Ex: ID du SMS de confirmation M-Pesa / Orange Money",
                        max_length=100,
                        verbose_name="ID / Référence de transaction Mobile Money",
                    ),
                ),
                (
                    "statut_paiement",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente de paiement"),
                            ("valide", "Paiement Validé / Payé"),
                            ("rembourse", "Remboursé"),
                        ],
                        default="en_attente",
                        max_length=20,
                        verbose_name="Statut du paiement",
                    ),
                ),
                (
                    "statut_commande",
                    models.CharField(
                        choices=[
                            ("nouvelle", "Nouvelle commande"),
                            ("en_preparation", "En préparation"),
                            ("prete", "Prête pour retrait"),
                            ("livree", "Livrée / Remise au client"),
                            ("annulee", "Annulée"),
                        ],
                        default="nouvelle",
                        max_length=20,
                        verbose_name="Statut du traitement",
                    ),
                ),
                (
                    "total_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Total USD ($)",
                    ),
                ),
                (
                    "notes_client",
                    models.TextField(
                        blank=True, verbose_name="Notes ou instructions particulières"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de commande"
                    ),
                ),
                (
                    "date_mise_a_jour",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commandes_shop",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Commande de la boutique",
                "verbose_name_plural": "Commandes de la boutique",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variante_label",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Taille / Option choisie",
                    ),
                ),
                (
                    "prix_unitaire_usd",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Prix unitaire ($)",
                    ),
                ),
                (
                    "quantite",
                    models.PositiveIntegerField(default=1, verbose_name="Quantité"),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shop.order",
                        verbose_name="Commande",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.product",
                        verbose_name="Article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article commandé",
                "verbose_name_plural": "Articles commandés",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="categorie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="shop.productcategory",
                verbose_name="Catégorie / Rayon",
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="shop/gallery/", verbose_name="Image additionnelle"
                    ),
                ),
                (
                    "legende",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Légende / Vue"
                    ),
                ),
                (
                    "ordre",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="shop.product",
                        verbose_name="Produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image additionnelle",
                "verbose_name_plural": "Images additionnelles",
                "ordering": ["ordre", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_variante",
                    models.CharField(
                        help_text="Ex: Taille S, Taille M, Taille L, U12, Ballon T7, etc.",
                        max_length=80,
                        verbose_name="Déclinaison / Taille",
                    ),
                ),
                (
                    "stock",
                    models.IntegerField(default=10, verbose_name="Stock spécifique"),
                ),
                (
                    "prix_supplementaire",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=8,
                        verbose_name="Supplément de prix ($)",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="shop.product",
                        verbose_name="Produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variante / Taille",
                "verbose_name_plural": "Variantes / Tailles",
                "ordering": ["nom_variante"],
            },
        ),
    ]
