# Generated by Django 5.1 on 2025-11-20 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('cible', models.CharField(choices=[('tous', 'Tous les membres'), ('categorie', 'Par catégorie'), ('individuel', 'Membres sélectionnés')], default='tous', max_length=50)),
                ('membres_cibles', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
