# Generated by Django 5.1 on 2025-12-10 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annonce',
            options={'ordering': ['-date_publication']},
        ),
        migrations.AddField(
            model_name='annonce',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annonce',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='membres_cibles',
            field=models.ManyToManyField(blank=True, related_name='annonces_ciblees', to=settings.AUTH_USER_MODEL),
        ),
    ]
