# Generated by Django 5.2.14 on 2026-07-08 08:25

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Annonce = apps.get_model("announcements", "Annonce")
    used_slugs = set(
        Annonce.objects.exclude(slug__isnull=True)
        .exclude(slug="")
        .values_list("slug", flat=True)
    )

    for announcement in Annonce.objects.all().order_by("pk"):
        if announcement.slug:
            continue

        base_slug = slugify(announcement.titre) or f"annonce-{announcement.pk}"
        slug = base_slug
        counter = 2

        while slug in used_slugs:
            slug = f"{base_slug}-{counter}"
            counter += 1

        used_slugs.add(slug)
        Annonce.objects.filter(pk=announcement.pk).update(slug=slug)


class Migration(migrations.Migration):

    dependencies = [
        (
            "announcements",
            "0002_alter_annonce_options_annonce_auteur_annonce_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="annonce",
            name="date_debut",
            field=models.DateTimeField(
                blank=True,
                help_text="À remplir pour une session ou un événement.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="annonce",
            name="date_fin",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="annonce",
            name="inscription_url",
            field=models.URLField(
                blank=True, help_text="Lien d'inscription ou de contact si disponible."
            ),
        ),
        migrations.AddField(
            model_name="annonce",
            name="lieu",
            field=models.CharField(
                blank=True, default="Terrain principal, Gombe, Kinshasa", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="annonce",
            name="resume_seo",
            field=models.CharField(
                blank=True,
                help_text="Résumé court utilisé par Google, ChatGPT et les partages sociaux.",
                max_length=180,
            ),
        ),
        migrations.AddField(
            model_name="annonce",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="annonce",
            name="type_annonce",
            field=models.CharField(
                choices=[
                    ("actualite", "Actualité"),
                    ("session", "Session de basket"),
                    ("evenement", "Événement"),
                    ("parcours", "Parcours / programme"),
                ],
                default="actualite",
                max_length=20,
            ),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
    ]
